version: '3'

networks:
  saber-stack:
    driver: bridge

volumes:
  mysql-data:
  minio-data:

services:

  saber:
    build: .
    hostname: saber
    restart: always
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=com.liukunup.saber.application.py
      - FLASK_CONFIG=docker
      - SUPER_ADMIN=Administrator
      - MYSQL_HOST=dbserver
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    links:
      - mysql:db-server
      - minio:oss-server
    depends_on:
      - mysql
      - minio
    networks:
      - saber-stack

  mysql:
    container_name: mysql-srv
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - saber-stack

  minio:
    container_name: minio-srv
    image: minio/minio:${MINIO_VERSION}
    hostname: minio
    restart: always
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    networks:
      - saber-stack
