"""Init

Revision ID: 59fe01b56cf7
Revises: 
Create Date: 2022-07-24 00:46:13.511612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fe01b56cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录编号'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='角色'),
    sa.Column('default', sa.Boolean(), nullable=True, comment='是否为默认角色'),
    sa.Column('permissions', sa.Integer(), nullable=True, comment='权限'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录编号'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('access_key', sa.String(length=32), nullable=False, comment='公钥'),
    sa.Column('secret_key', sa.String(length=32), nullable=False, comment='私钥'),
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色ID'),
    sa.Column('owner', sa.String(length=256), nullable=False, comment='所有者(工号或昵称)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否已被启用'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_access_key'), 'user', ['access_key'], unique=True)
    op.create_table('audit',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('event', sa.String(length=256), nullable=False, comment='事件'),
    sa.Column('args', sa.JSON(), nullable=True, comment='参数'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    op.drop_index(op.f('ix_user_access_key'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
